Added a $destroyfifo option.
git-svn-id: https://mylvmdump.svn.sourceforge.net/svnroot/mylvmdump/trunk@51 7d41abeb-baf7-48f7-bffb-9f7dbff3a22f

diff --git a/mylvmdump b/mylvmdump
--- a/mylvmdump
+++ b/mylvmdump
@@ -193,8 +193,11 @@ snapshot() {
 	bool uselvm || return
 	# Check whether the FIFO exists.
 	if [ -e "$fifo" ]; then
-		# TODO: Create a 'destroyfifo' option.
-		die "FIFO '$fifo' already exists."
+		if bool destroyfifo; then
+			rm "$fifo" || die "Could not destroy FIFO '$fifo'."
+		else
+			die "FIFO '$fifo' already exists."
+		fi
 	fi
 	# Create the FIFO.
 	mkfifo -m 0600 "$fifo" || die "Could not create FIFO '$fifo'."
