FIFO construct for locking MySQL before snapshot.
git-svn-id: https://mylvmdump.svn.sourceforge.net/svnroot/mylvmdump/trunk@38 7d41abeb-baf7-48f7-bffb-9f7dbff3a22f

diff --git a/mylvmdump b/mylvmdump
--- a/mylvmdump
+++ b/mylvmdump
@@ -10,6 +10,9 @@ PARSEABLE='--skip-column-names'
 # Initial set of mysqldump options to use.
 DUMPOPTS='--skip-opt --add-drop-table --add-locks --create-options --disable-keys --extended-insert --quick --set-charset'
 
+# MySQL command to run before snapshotting.
+FLUSHCMD='FLUSH TABLES WITH READ LOCK'
+
 # Exit with an error message.
 die() {
 	echo "$1"
@@ -162,6 +165,34 @@ gettablesmatching() {
 	done
 }
 
+# Create an LVM snapshot of the database.
+snapshot() {
+	# Check whether the FIFO directory exists.
+	if [ -e "$fifodir" ]; then
+		# TODO: Create a 'destroyfifo' option.
+		die 'FIFO directory already exists.'
+	fi
+	# Create the FIFO directory and the FIFOs inside.
+	if mkdir "$fifodir"; then
+		for fifo in 'command' 'reply'; do
+			if ! mkfifo -m 0600 "$fifodir/$fifo"; then
+				rm -rf "$fifodir"
+				die "Could not create FIFO '$fifo'."
+			fi
+		done
+	else
+		die "Could not create FIFO directory '$fifodir'."
+	fi
+	echo "$FLUSHCMD;" > "$fifodir/command" &
+	statusreturned=''
+	runwithcfg mysql -v -v -n < "$fifodir/command" | grep --line-buffered -Ev "^(|-.*|$FLUSHCMD;?)\$" | while read line; do
+		if [ -z "$statusreturned" ]; then
+			statusreturned=y
+			echo -e 'UNLOCK TABLES;\n\q' > "$fifodir/command"
+		fi
+	done
+}
+
 # The main backup act.
 backup() {
 	# Retrieve the list of databases.
@@ -268,6 +299,7 @@ namepattern='$(date "+%Y-%m-%d_%H-%M-%S")_${database}.sql${compresssuffix}'
 temppattern='$dumpname.tmp'
 dbfilterdefault='+'
 tablefilterdefault='+'
+fifodir='fifos'
 
 # Read command-line options.
 purgeonly=n
@@ -338,6 +370,7 @@ fi
 
 # If we're not only purging, we're actually doing backups. Yay!
 if ! bool purgeonly; then
+	snapshot
 	backup
 fi
 
